python scripts/demographs_creation/create_demograph.py \
    --ignoreErrors  \
    --country="us" \
    --metadatayear=2020 \
    --unitspath=data/us/us_geounits_cc-est_2023.csv \
    --subunitspath= \
    --genderdistpath=data/us/us_genre_distribution_cc-est_2023.csv \
    --agedistpath=data/us/us_age_distribution_cc-est_2023.csv \
    --usersdatapath=data/us/us_metadata_epo_2023.csv \
    --stopwords='of|the|county|district' \
    --ignoreErrors && \
python scripts/demographs_creation/create_demograph.py \
    --country="us" \
    --ignoreErrors  \
    --metadatayear=2023 \
    --unitspath=data/us/us_geounits_cc-est_2023.csv \
    --subunitspath= \
    --genderdistpath=data/us/us_genre_distribution_cc-est_2023.csv \
    --agedistpath=data/us/us_age_distribution_cc-est_2023.csv \
    --usersdatapath=data/us/us_metadata_epo_2023.csv \
    --stopwords='of|the|county|district' \
    --ignoreErrors && \
python scripts/demographs_creation/create_demograph.py \
    --country="us" \
    --ignoreErrors \
    --metadatayear=2025 \
    --unitspath=data/us/us_geounits_cc-est_2023.csv \
    --subunitspath= \
    --genderdistpath=data/us/us_genre_distribution_cc-est_2023.csv \
    --agedistpath=data/us/us_age_distribution_cc-est_2023.csv \
    --usersdatapath=data/us/us_metadata_epo_2023.csv \
    --stopwords='of|the|county|district' \
    --ignoreErrors
